#!/usr/bin/env node
/**
 * npm run content:measure
 *
 * Replaces guessed time budgets with measured ones.
 *
 * Two things get measured:
 *
 *  1. Each mission's reference solution at perf.scale, so `optimalMs` reflects
 *     what the optimal answer actually costs rather than an estimate.
 *
 *  2. The Python weight factor. Pyodide is slower than V8, but "about 4×" was a
 *     guess. This runs the same workload under both and computes the real ratio,
 *     so Python players are not judged against JavaScript timings.
 *
 * Results are written back into mission.json (perf.optimalMs) and into
 * content/calibration.json. Pass --dry to preview without writing.
 */
import fs from 'node:fs'
import path from 'node:path'
import { loadAll, c, time, projectNaive } from './lib.mjs'
import { makeRng } from '../../content/lib/rand.js'

const round = (n) => Math.round(n * 100) / 100

const DRY = process.argv.includes('--dry')
const SKIP_PYTHON = process.argv.includes('--no-python')

// ── Python calibration ──────────────────────────────────────────────────────
// A deliberately plain integer/list workload — no library calls, so it measures
// interpreter overhead rather than one runtime's optimised builtins.
const JS_WORKLOAD = (n) => {
  let acc = 0
  const a = []
  for (let i = 0; i < n; i++) a.push((i * 7919) % 1000)
  for (let i = 0; i < n; i++) { acc += a[i]; if (a[i] > 500) acc -= 1 }
  return acc
}
const PY_WORKLOAD = `
def workload(n):
    acc = 0
    a = []
    for i in range(n):
        a.append((i * 7919) % 1000)
    for i in range(n):
        acc += a[i]
        if a[i] > 500:
            acc -= 1
    return acc
`

async function calibratePython() {
  const N = 300000
  const jsMs = time(() => JS_WORKLOAD(N), 5)

  const { loadPyodide } = await import('pyodide')
  const py = await loadPyodide()
  py.runPython(PY_WORKLOAD)
  const fn = py.globals.get('workload')
  const pyMs = time(() => fn(N), 3)

  return { n: N, jsMs, pyMs, weight: Math.max(1, pyMs / jsMs) }
}

// ── Run ─────────────────────────────────────────────────────────────────────
const missions = await loadAll()
console.log(c.bold('\nMeasuring reference solutions\n'))

const updates = []
for (const m of missions) {
  const x = m.meta
  if (!x.perf) {
    console.log(`${c.dim('skip')}  ${x.id}  ${c.dim('no perf gate')}`)
    continue
  }
  const args = m.gen(makeRng(7), x.perf.scale)
  const ms = time(() => m.ref(...args), 7)
  const proj = m.naive ? projectNaive(m.naive, m.gen, x.perf.scale) : null

  updates.push({ m, optimalMs: round(ms) })
  console.log(
    `${c.green('meas')}  ${x.id}  n=${x.perf.scale.toLocaleString()}  ` +
    `reference ${c.bold(ms.toFixed(1) + ' ms')}  ` +
    (proj ? c.yellow(`naive projects to ${fmt(proj.projectedMs)} (${(proj.projectedMs / ms).toFixed(0)}×)`) : c.dim('no naive supplied'))
  )
  if (ms < 3) {
    console.log(`      ${c.yellow('warn')}: reference runs in under 3 ms — timing noise will dominate. ` +
      `Consider raising perf.scale so ratings are stable.`)
  }
}

let calibration = null
if (!SKIP_PYTHON) {
  console.log(c.bold('\nCalibrating Python runtime (loads Pyodide, ~20 s)\n'))
  try {
    calibration = await calibratePython()
    console.log(
      `${c.green('meas')}  identical workload at n=${calibration.n.toLocaleString()}: ` +
      `JavaScript ${calibration.jsMs.toFixed(0)} ms, Python ${calibration.pyMs.toFixed(0)} ms`
    )
    console.log(`      measured Python weight: ${c.bold(calibration.weight.toFixed(2) + '×')}`)
  } catch (err) {
    console.log(`${c.yellow('warn')}  Python calibration unavailable (${err.message}). Keeping the existing weight.`)
  }
}

if (DRY) {
  console.log(c.dim('\n--dry: nothing written.\n'))
  process.exit(0)
}

for (const u of updates) {
  const p = path.join(u.m.base, 'mission.json')
  const json = JSON.parse(fs.readFileSync(p, 'utf8'))
  json.perf.optimalMs = u.optimalMs
  fs.writeFileSync(p, JSON.stringify(json, null, 2) + '\n')
}
if (calibration) {
  fs.writeFileSync(
    path.resolve('content/calibration.json'),
    JSON.stringify({
      measuredAt: new Date().toISOString(),
      note: 'Generated by npm run content:measure. Do not edit by hand.',
      workloadN: calibration.n,
      javascriptMs: round(calibration.jsMs),
      pythonMs: round(calibration.pyMs),
      weights: { javascript: 1, python: round(calibration.weight) }
    }, null, 2) + '\n'
  )
}
console.log(c.green(`\nWrote ${updates.length} mission budget(s)${calibration ? ' and calibration.json' : ''}.\n`))

function fmt(ms) {
  if (ms > 60000) return `${(ms / 60000).toFixed(1)} min`
  if (ms > 1000) return `${(ms / 1000).toFixed(1)} s`
  return `${ms.toFixed(0)} ms`
}
